version: '3.9'

networks:
  bookstoretest:

services:
  db_test:
    image: mysql:5.7
    container_name: db_test
    build:
      context: ./scripts
    volumes:
      - "./scripts/db.sql:/docker-entrypoint-initdb.d/db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3407:3306'
    networks:
      bookstoretest:
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    tty: true
    restart: on-failure
  tests:
    container_name: tests
    build:
      context: ./cmd/app
      dockerfile: ./Dockerfile.test
    volumes:
      - ./bin:/go"
    env_file: .env
    ports:
      - "8082:8082"
    networks:
      bookstoretest:
    depends_on:
      - db_test
    links:
      - db_test
    #command:  ["./wait-for-it.sh", "db_test:3306", "--", "go", "test", "./..."]
    tty: true



